.gitignore, python/idsse_common/README.md, python/idsse_common/idsse/common/aws_utils.py, python/idsse_common/idsse/common/path_builder.py, python/idsse_common/test/test_aws_utils.py, python/idsse_common/test/test_path_builder.py
- Add unit tests for `PathBuilder` and `AwsUtils` python classes with at least 80% code coverage
- Made some minor changes to `PathBuilder` to handle error cases more gracefully, made apparent by inconsistent unit tests. 
- E.g checking that `lead.hour` exists in arguments before attempting to build `lead` timedelta
- Remove manual validation `_test()` functions that were serving the purpose of unit/regression tests
- Add comments to PathBuilder explaining issue/valid/lead terminology
- Update readme with steps to generate pytest code coverage report
```
---------- coverage: platform darwin, python 3.11.4-final-0 ----------
Name                                               Stmts   Miss  Cover
---------------------------------------------------------------------- …
```
=> Feature: PathBuilder and AwsUtils tests

python/idsse_common/idsse/common/aws_utils.py, python/idsse_common/idsse/common/config.py, python/idsse_common/idsse/common/log_util.py, python/idsse_common/idsse/common/publish_confirm.py, python/idsse_common/idsse/common/utils.py, python/idsse_common/test/test_aws_utils.py
Correct some python type hint decorators which didn't match the actual runtime variables returned from functions in `aws_utils.py` and `utils.py`. 
- For example, functions that return a `Sequence`, or sometimes `None` on error, were annotated to always return a `Sequence`. 
- Or a function parameter which default to `None` was typed as non-null, so linters would complain if you omitted the parameter but the code would execute without issue.
=> Chore: fix python type hints

python/idsse_common/idsse/common/log_util.py, python/idsse_common/idsse/common/publish_confirm.py
N/A
Calling `get_default_log_config()` with `with_corr_id=False` was still expecting a `corr_id` to exist in the filters that it passed to logging.config.
This would cause the following exception to be thrown as soon as the caller class attempted to use their logger:
```sh
Traceback (most recent call last):
File "lib/python3.11/logging/__init__.py", line 974, in handle
rv = self.filter(record)
^^^^^^^^^^^^^^^^^^^
File "lib/python3.11/logging/__init__.py", line 830, in filter
result = f.filter(record)
^^^^^^^^^^^^^^^^
File "idss-engine-commons/python/idsse_common/idsse/common/log_util.py", line 52, in filter
record.corr_id = corr_id_context_var.get()
LookupError: <ContextVar name='correlation_id' at 0x104b40db0>
```
- `filters:` in logging config only has `corr_id` if it's also in the …
=> Bug: log util errors without correlation ID

python/idsse_common/idsse/common/aws_utils.py, python/idsse_common/idsse/common/log_util.py, python/idsse_common/idsse/common/utils.py
While working on Linear 348 (benchmarking converting vector to raster) can across an indentation error and some other small linter issues. 
There are a couple of lines that were more than 100 char long, which I split onto two lines. I don't think we have formally addressed line length, but my take on it is: We can allow up to 120, but should try to keep them at 100. I have two reasons for this, 1) there has been studies that show line length up to 99 are easily readable but after that there is impact, and 2) with my screen resolution, font size, and window size, It gets harder when lines are over 100, often I have to scroll left/right.
=> Small cleanup

.github/workflows/run-tests.yml
N/A
- Update pytest GitHub Actions workflow to install all dependencies with conda
- Missing dependency `pygrib` was causing test coverage to be artificially low, but attempting to install pygrib with `pip` threw errors, causing tests to fail
We can revert this change (use pip to install dependencies again) after [IDSSE-352](https://linear.app/idss/issue/IDSSE-352) is completed (refactor `shrink_grib()` util into Data Access Service)
=> Chore: fix pytest runner coverage

python/idsse_common/test/test_validate_schema.py
Linear 335
The task was to write and test a schema that can be used to validate AvailableData requests. The schema was already written so I simply added the tests. There are four types of AvailableData request, request for issue(s), valid(s), lead(s), field(s).
=> JSON Schema for AvailableData Request

python/idsse_common/idsse/common/publish_confirm.py
N/A
- Modify publish_confirm._records object to use [Python dataclass](https://docs.python.org/3/library/dataclasses.html?highlight=dataclass#dataclasses.dataclass) instead of NamedTuple
PublishConfirm was unusable in its current state, throwing an exception every time you called `publish_message()`:
```
AttributeError("'PublishedMessages' object attribute 'message_number' is read-only")
```
This was due to `self._records` being a NamedTuple--all attributes are immutable. NamedTuple was a poor choice on my part, since the _records object specifically exists to track (and update) message metrics like `message_number`. 
There is a possible solution where you re-assign the entire NamedTuple using `NamedTuple._replace()` every time any attribute changes, for example:
```python
self._records = …
```
=> Bug: publish_confirm error "message_number is read-only"

python/idsse_common/idsse/common/grid_proj.py, python/idsse_common/test/test_grid_proj.py
Linear - 361
I didn't feel up for do much but was up for cleaning up GridProj so I created a task.
Basically, 
crs is used for Coordinate Reference System, which is what pyproj maps lat/lon to and from, previous 'geo' was used which stood for geospatial reference system.
geo is used as short hand for geographic (ie lat/lon space), previously proj was used
pixel is unchanged
I did find and replaces according to above changes, added (extended) docstrings, and added some properties and helper methods.
There will be an accompanying PR for DAS to adjust to these changes.
=> GridProj cleanup

python/idsse_common/idsse/common/json_message.py, python/idsse_common/idsse/common/log_util.py, python/idsse_common/idsse/common/path_builder.py, python/idsse_common/test/test_json_message.py, python/idsse_common/test/test_log_util.py, python/idsse_common/test/test_path_builder.py
N/A
- Type hint cleanup for json_message.py
- Add unit tests to cover json_message.py
- Add unit tests to cover log_util.py
- Remove unused code in path_builder.py that was hurting its coverage report
With these additions we should be above 90% coverage for this library.
=> Feat: unit tests for json_message and log_util

python/idsse_common/idsse/common/publish_confirm.py, python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/test/test_publish_confirm.py
[IDSSE-429](https://linear.app/idss/issue/idsse-429)
- On `publish_message()`, if RabbitMQ connection or channel are not ready, PublishConfirm will call setup methods internally, wait until they complete, then publish message.
Previously we required users of PublishConfirm class to call `start()` before publishing any messages, and raised an exception if they skipped that step. Now a PublishConfirm can effectively be used right after it is instantiated, without any external callbacks provided.
```python
pub_conf = PublishConfirm(params) # assume some valid RabbitMQ params
pub_conf.publish_message({'data': [123]})  # should succeed
```
_Note: callers can still invoke `start()` if they want. This will complete the exact same setup that publish_message() calls automatically when they attempt …
=> bug: idsse-429: PublishConfirm wait for internal setup

python/idsse_common/idsse/common/schema/das_web_request.json, python/idsse_common/test/test_validate_das_web_schema.py
Linear 473
This is a subtask of Linear 442 (PR in DAS), which now assumes coordinates are now always (x,y) and support two different structures for the bounding box in the json request. This PR is the corresponding update to the schema for the additional valid structure. 
Previously support struct:
`"bbox": {
"botLeft": [100, 102],
"topRight": [200, 202]
}`
New (additional) struct:
`"bbox": [[100, 102],  [200, 202]]`
=> Support bounding box "bbox" as list of list

python/idsse_common/idsse/common/schema/risk_results.json, python/idsse_common/setup.py, python/idsse_common/test/test_validate_event_port_schema.py
Linear - 488
First step in updating the EventPort to support IMS Response. With this PR 'evaluatedAt' (iso datetime string) is a required key/value in 'riskResult' object. In original EventPort json this value was keyed as 'timeStamp' but was inadvertently dropped with the new EventPort spec. 
The changes to setup.py were required to have the messages schema (json files) to be included in the idsse-commons package. Previously this worked without the "include_package_data=True" but it seems to be needed now.
=> Add 'evaluatedAt' to EventPort

python/idsse_common/idsse/common/publish_confirm.py, python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/test/test_publish_confirm.py
- [IDSSE-423](https://linear.app/idss/issue/idsse-423) - handle null connection/channel
- [IDSSE-441](https://linear.app/idss/issue/idsse-441) - consolidate pass-through methods
- Consolidate small methods that only exist to be called one time by another method.
- Add `None`-check around any usage of self._connection or self._channel
- They can technically be None, but they never should be after connection/channel is initialized
- When possible, use the `connection` arg that pika passes to our callbacks to avoid using the private variable at all.
- Block attempts to call `PublishConfirm.start()` more than once
- This is same behavior as calling Python Thread.start() twice
Also a minor addition to `rabbitmq_utils`:
- Added a `connection_parameters` property to `Conn` data object. 
- This …
=> chore: IDSSE-441: PublishConfirm internal cleanup

python/idsse_common/idsse/common/schema/risk_results.json, python/idsse_common/test/test_validate_event_port_schema.py
Linear 502
This is the first part in getting our sample eventPorts up to date. This is the update to the eventPort schema to require the dataDescript, which hold the info about what/where the raw data was accessed.
=> Added dataDescript to EventPort

python/idsse_common/idsse/common/schema/risk_results.json, python/idsse_common/test/test_validate_event_port_schema.py
Linear 502
Last part of updating eventPort, corrected regex to include support for scientific notation.
=> Updated regex to match scientific notation

python/idsse_common/idsse/common/utils.py, python/idsse_common/idsse/common/vectaster.py, python/idsse_common/test/test_vectaster.py
N/A
- Add `geographic_point_to_pixel()` to vectaster module
- If `geographic_to_pixel()` is passed a shapely.Point object, call this new function and return
- Previously would throw an error saying "object must be a Polygon or a LineString"
We could have just reformatted this Point as a LineString size 1 and needed less additional code, but it felt more accurate for the `geographic_to_pixel()` function to return the same shapely type that was passed.
=> Bug: Add support for Point shape to geometric_to_pixel

python/idsse_common/test/test_geo_image.py
N/A
A few unit tests in the main branch, and had been since PR #47 was merged. 
I modified the expected values slightly in `test_geo_image.py` so that they pass. Not clear what code changes in geo_image.py caused these to fail, but in most cases the value was only shifted by a few pixels.
Also have no idea why the GitHub Action displays as " :white_check_mark: Success", yet running pytest locally, or looking at logs in GitHub [on the main branch](https://github.com/NOAA-GSL/idss-engine-commons/actions/runs/7534584778/job/20509196123#step:6:248) or [on the original branch](https://github.com/NOAA-GSL/idss-engine-commons/actions/runs/7490471145/job/20389404908#step:6:248), outputs these failing tests.
=> Chore: fix expected data in test_geo_image

python/idsse_common/idsse/common/validate_schema.py
Linear - 522
As of jsonschema 4.18 (I think) the use of RefResolver has been deprecated in preference of Registry. There is very little code changes here, and all within one file.
Note: This code requires jsonschema to be version 4.21 (or beyond) and a new package 'referencing'. I installed both with pip.
=> Remove deprecated RefResolver jsonschema validataion

.github/workflows/linter.yml, .github/workflows/run-tests.yml
[IDSSE-558](https://linear.app/idss/issue/IDSSE-558)
- In GitHub Action, set pytest to exit immediately on failure.
We pipe the output of `pytest` to `tee`, which dumps output to a txt file for test coverage reports later. However, this was eating the exit code of pytest, so `tee` would exit 0 and GitHub called the tests "passing", even when pytest exited nonzero due to failing tests
=> bug: set pytest to exit on failure

python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/test/test_rabbitmq_utils.py
[IDSSE-763](https://linear.app/idss/issue/IDSSE-763)
- Create `PublisherSync` class, which connects to RabbitMQ on init, has a `publish_message()` method like PublishConfirm, and a `close()` method to cleanup connection
Unlike PublishConfirm, this class does not manually track or guarantee message delivery, and does not create a separate thread to ensure thread safety. Just a simple wrapper of pika's `basic_publish()` to send messages (_probably_) to a given exchange & queue.
PublishConfirm has been experiencing some strange thread lock issues which prevent it from starting up and connecting to RabbitMQ. They've only occurred in the dev environment so far (haven't been replicated locally).
This utility class will at least simplify troubleshooting for services like RiskProcessor while we …
=> feat: idsse-763: simple pika RMQ publisher

python/idsse_common/idsse/common/rabbitmq_utils.py
[IDSSE-788](https://linear.app/idss/issue/IDSSE-788)
- Save off connection param to use if basic publish fails
- On basic publish fail, reconnect and try again
- PublisherSync no longer can take a preexisting BlockingConnection, only params
I did not at testing for this since I don't know how and PublisherSync is being used temporarily
=> Chore/idsse 788/add reconnect

python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/test/test_rabbitmq_utils.py
[IDSSE-795](https://linear.app/idss/issue/IDSSE-795)
- Add a `stop()` method to PublisherSync class
Now `PublisherSync` class will have the same public methods as `PublishConfirm`. 
This way the cutover from using PublisherSync back to using PublishConfirm should be seamless--we only need to instantiate one class or the other, and all other methods will just work.
=> chore: add stop() method to PublisherSync

python/idsse_common/idsse/common/aws_utils.py
[IDSSE-912](https://linear.app/idss/issue/IDSSE-912)
- Add optional `concurrency` and `chunk_size` args to aws_cp, to change how s5cmd downloads files (hopefully improving the time to download a large file)
These function args let us control the number of parallel threads and size of chunks that s5cmd uses to download a single GRIB file from AWS. The defaults (what DAS was using up until now) is 5 threads, 50 MB chunks at a time, but now DAS can tweak these controls to figure out what runs the fastest in our environment.
Unfortunately s5cmd does not support downloading partial files from AWS S3 today. It's open source, so I'm hoping to contribute to the s5cmd project to get it added.
=> feat: idsse-912: add optimization args to `aws_cp()`

python/idsse_common/idsse/common/aws_utils.py
N/A
- Fix bug in `aws_cp()` utility that attempted to pass non-string arguments to the exec_cmd. The underlying os command that it calls requires everything to be strings. 
N/A
=> bug: aws_cp optional args should not be ints

python/idsse_common/idsse/common/rabbitmq_utils.py
N/A
- Small bug fix for RabbitMQ Publisher and Consumer class `__init__`s to pass the right argument type to `pika.BlockingConnection`.
The rabbitmq class property `Conn` has a property `connection_parameters` that transforms the NamedTuple that a caller would have created into a `pika.ConnectionParameters` which `pika.BlockingConnection` expects. However, we forgot to use this transformation throughout rabbitmq_utils.py. 
For example, passing an `Conn` instance to `Publisher()` was throwing an uncaught exception:
```
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/mackenzie.grimes/dev/idss-engine-commons/python/idsse_common/idsse/common/rabbitmq_utils.py", line 434, in __init__
self.connection = BlockingConnection(conn_params)
AttributeError: 'str' object has no attribute …
```
=> bug: pass Conn.connection_parameters to pika.BlockingConnection

python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/test/test_rabbitmq_utils.py
[IDSSE-860](https://linear.app/idss/issue/IDSSE-860)
- While working on Linear 860 I decided it would be cleaner to not have the queue type (classic) part of the default 'arguments' dictionary (it is the default if no type is specified)
N/A
=> Removed default Queue argument dict

python/idsse_common/idsse/common/rabbitmq_utils.py
[IDSSE-xxx](https://linear.app/idss/issue/IDSSE-xxx)
- List of high-level changes
N/A
=> Fixed KeyError where 'x-queue-type' was assumed to be in args

python/idsse_common/idsse/common/log_util.py, python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/test/test_log_util.py
[IDSSE-1011](https://linear.app/idss/issue/IDSSE-1011)
- There wasn't so much as a bug, as missing logic
- We use python's ContextVars to make corr_id available to logging
- It turns out that a thread doesn't inherit ContextVars automatically
- There are two ways to get logs from threads
- 1) We can initialize our logger to not use corr_id `logging.config.dictConfig(get_default_log_config('INFO', with_corr_id=False))`
- 2) Pass ContextVars to threads
- I added tests two test_log_util.py that test getting logs from a thread running a function and from Classes that extend Threads
- I added passing ContextVars to Consume/Publisher in rabbitmq_utils.py
- There are likely other places in our code that logs are getting lost in threads, and the test in log_util.py will serve as example code
N/A
=> Lost logs from threads

python/idsse_common/idsse/common/rabbitmq_utils.py
[IDSSE-897](https://linear.app/idss/issue/IDSSE-897)
Shorter interim PR so the soon-to-exist `rabbitmq_utils.Rpc` class can reuse as much Publisher logic as possible.
- Move some Publisher internal methods out into module-wide rabbitmq_utils functions
- Default Consumer `num_message_handlers` to `2`.
- We are usually passing `2` in actual usages of the Consumer class, because the caller doesn't usually care or know any better.
- Bug fix: Publisher and Consumer avoid attempting to declare or bind the default RabbitMQ exchange or queue
- Previously if you tried to instantiate a Publisher or Consumer passing the default exchange/queue, as RPC Direct Reply-to does, RabbitMQ would throw a fatal error. 
N/A
=> feat: idsse-897: minor Publisher refactor

python/idsse_common/idsse/common/schema/gateway_web_request.json, python/idsse_common/idsse/common/schema/gateway_web_request_schema.json, python/idsse_common/idsse/common/schema/support_profile.json
[IDSSE-1071](https://linear.app/idss/issue/IDSSE-1071)
- Add jsonschema to validate HTTP requests to NWSC Gateway webserver
- Add `SupportProfile` jsonschema based on our example responses from NWS Connect API from Jan 2024. 
- Only the couple of fields used to translate Support Profiles into Criteria are required. Everything else is documented but optional (unused)
- E.g. `id`; `geomAsString`; `dataSource`, `environmentalConditionType`, `units` `value`, of each condition part, etc.) 
N/A
=> add gateway_web_request, support_profile jsonschema

python/idsse_common/idsse/common/schema/field.json, python/idsse_common/idsse/common/schema/product.json
[IDSSE-1076](https://linear.app/idss/issue/IDSSE-1076)
- Add "MRMS" product and "CREF" field to their respective JSON schemas
DAS New Data service was publishing new data messages that were technically "invalid" for the product MRMS, so a service consuming these messages may reject it if they compared it against the jsonschema validator.
=> add 'CREF' as accepted Field string

python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/test/test_rabbitmq_utils.py
[IDSSE-1066](https://linear.app/idss/issue/IDSSE-1066)
- Update the use of UUID as a corelation_id in the  properties of a RMQ message request/respond actions for RPC. 
Initial implementation for consistent use o  correlation_id in RMQ messages
=> Idsse 1066

python/idsse_common/idsse/common/aws_utils.py, python/idsse_common/test/test_aws_utils.py
[IDSSE-1124](https://linear.app/idss/issue/IDSSE-1124)
- Catch PermissionError from s5cmd `cp()` and consider the copy failed
Example error from the logs:
```
PermissionError: [Errno 1] ERROR ['cp', 
's3://noaa-nbm-grib2-pds/blend.20250212/21/core/blend.t21z.core.f015.co.grib2.idx',
'/local_data/tmp/NBM.AWS.GRIB/CONUS/2025/02/12/NBM.AWS.GRIB_CONUS_20250212210000_20250213120000.grib2.idx"'] \
: NoSuchKey: The specified key does not exist. status code: 404, request id: 6RK36H29SDDK1FPD, host id: qHKluGgOENa7M3mpA95CI7cGQQ6TOGyfD6098UNTcf5mH2uSC2QkpGLZiNR8dyXeEhw26djYa7A=
```
This 404 means the file we tried to download doesn't exist in the S3 bucket (yet). By returning False, we can allow function callers to retry, rather than throwing an uncaught exception. 
DAS [already has retry …
=> bug: AWS permission error when FileNotFound

python/idsse_common/idsse/common/schema/field.json
[IDSSE-1124](https://linear.app/idss/issue/IDSSE-1124)
- Change the field.json schema (used by New Data) to allow the string `DewPoint`, which matches other DAS constants (not `Dewpoint`)
N/A
=> bug: field.json schema DewPoint

python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/test/test_rabbitmq_utils.py
[IDSSE-1135](https://linear.app/idss/issue/IDSSE-1135)
- `Consumer`: copy `context` of Consumer to any ThreadPoolExecutor threads
- Previously, no log messages from Consumer `on_message` callbacks were making it to the console due to this bug, except calls to functions like `threadsafe_ack()`.
- `rabbitmq_utils.Rpc`: nack any response message that can't be correlated with a request based on `properties.headers.rpc`
- This quirk where RPC silently ignores any "unregistered" response message hid [a bug in DAS](https://github.com/NOAA-GSL/data-access-service/pull/144). We figured it out, but this logging will surface issues like that sooner.
N/A
=> bug: idsse-1135: Consumer callbacks not logging

python/idsse_common/idsse/common/protocol_utils.py, python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/test/test_rabbitmq_utils.py
[IDSSE-1153](https://linear.app/idss/issue/IDSSE-1153)
- Just added optional key/word args
- All other changes were to fix linter
N/A
=> Add keyword args to get passed to path builder

python/idsse_common/idsse/common/rabbitmq_rpc.py, python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/test/test_rabbitmq_rpc.py, python/idsse_common/test/test_rabbitmq_utils.py
[IDSSE-1142](https://linear.app/idss/issue/IDSSE-1142)
- Create `RpcPublisher`
- `Rpc` class with more specific name. We will delete `Rpc` after all usages in IDSSe services have been migrated
- Fix minor bug where `Rpc.send_request()` defined its own, hard-coded message properties (`application/json`, for example). Now caller can pass the request message's BasicProperties
- Create `RpcConsumer` class
- Opposite of `RpcPublisher`, listens for Rpc requests, triggers some `on_message()` function you give it to form a response, then structures the response correctly for Rpc reply
Previously we had custom code in DAS that structured and published all its RPC responses in the way that `Rpc` expects. We'd rather have logic for both ends of the RPC in the same place, and we could theoretically …
=> chore: RpcPublisher and RpcConsumer classes

python/idsse_common/idsse/common/protocol_utils.py, python/idsse_common/test/test_aws_utils.py
[IDSSE-1215](https://linear.app/idss/issue/IDSSE-1215)
- ProtocolUtils.get_issues: set `issue_end` to dynamic `now()`, not a default arg in function signature
The most common usage of this function in DAS was 
```python
get_issues(num_issues=1, region='CONUS')
```
which left the `issue_end` arg as the default value. 
Because I put `datetime.now(UTC)` in the function signature (not in the body of the function), python was running `.now()` just once on startup (when protocol_utils.py was imported) rather than calling `.now()` every time the function was called as we intended. 
Therefore a DAS instance who received a `"sourceType": "issues"` request would always return the latest issueDt available when it started up--filtering out any newer issues that appeared on the AWS/HTTP server because …
=> bug: get_issues() returning same stale issueDt

python/idsse_common/idsse/common/sci/netcdf_io.py, python/idsse_common/idsse/common/utils.py, python/idsse_common/test/test_utils.py
[IDSSE-1164](https://linear.app/idss/issue/IDSSE-1164)
- Add `utils.FileBasedLock` 
Example:
```py
with FileBasedLock('my_file.grib2', max_age=30):
open('my_file.grib2', 'r') # ...
print('File released to other threads!')
```
These changes will make a blank `foo.<ext>.lock` file on the filesystem before reading from/writing to a `foo.<ext>` file. 
- If we find a .lock file already there, we loop waiting for it to disappear.
- If we've waited `max_age` seconds, we assume the thread that locked it is dead somehow, and we take over the file lock anyway.
Yes, but IDSSe can't always rely on that. Our services can be running on different Kubernetes nodes, or different containers in that node, or different Python/Gunicorn processes, and the filesystem they're reading/writing files from could be …
=> bug: add FileBasedLock (NFS proof)

python/idsse_common/idsse/common/utils.py, python/idsse_common/test/sci/test_netcdf_io.py, python/idsse_common/test/test_utils.py
N/A (hotfix)
- Ensure that all parent directories of the target FileBasedLock exist before trying to create a `.lock` file
The previous PR (#104), once used by DAS, was throwing uncaught exceptions:
```
FileNotFoundError: [Errno 2] No such file or directory: '/local_data/tmp/NBM/CONUS/2025/04/30/NBM_CONUS_20250430210000_20250501130000.grib2.idx.lock'
```
We failed to consider when FileBasedLock would be used to write data to a directory that didn't yet exist.
Now FileBasedLock will create (but not clean up) any parent directories above the provided filepath, before creating the `.lock`.
=> bug: FileBasedLock parent dir may not exist

python/idsse_common/idsse/common/schema/support_profile.json, python/idsse_common/idsse/common/utils.py
N/A
- Some logs have shown uncaught errors when a service attempts to release a FileBasedLock: `FileNotFoundError`. 
- If we try to release a file lock, and it's already released, catch the error and assume the lock can be abandoned.
N/A
=> bug: catch error on FileBasedLock release()

python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/idsse/common/schema/support_profile.json, python/idsse_common/idsse/common/utils.py, python/idsse_common/test/test_rabbitmq_utils.py
[IDSSE-1276](https://linear.app/idss/issue/IDSSE-1276)
- In RabbitMQ utils `Publisher.blocking_publish()`, confirm that RabbitMQ connection/channel is open before trying to publish
- If it isn't open, re-attempt connection and then publish message
- Default all RabbitMQ `Conn` to configure a `3600` second heartbeat from the RabbitMQ broker
- RabbitMQ library default is 60 seconds
- This might help prevent long-running connections from randomly getting closed by the broker. Might introduce new weird behavior across services though
We saw a bug in the dev environment where an instance of the NWSC Gateway had been idle for a while (days). When the Criteria Builder sent it a Support Profile to publish to RabbitMQ, it failed with an error message that the connection was in closed state. …
=> bug: idsse-1276: Publisher re-connect if connection closed

python/idsse_common/idsse/common/schema/event_portfolio_schema.json, python/idsse_common/idsse/common/schema/tags.json, python/idsse_common/test/test_validate_event_port_schema.py
[IDSSE-1292](https://linear.app/idss/issue/IDSSE-1292)
- Change Event Portfolio jsonschema: `riskResults` can be empty array
- Also add optional `tags.keyValues` attribute called `status`
Now the Risk Processor can create partial EPs with `status`: `PROCESSING` with an empty array of `riskResults`. This means the DSD can no longer assume `riskResults` will always be an array sized 1, as partially completed or failed EPs may have no results.
=> JsonValidator: allow partial Event Portfolios

python/idsse_common/idsse/common/rabbitmq_rpc.py, python/idsse_common/test/test_rabbitmq_rpc.py
[IDSSE-1243](https://linear.app/idss/issue/IDSSE-1243)
- `RpcPublisher.send_request()`: allow the `TimeoutError` to be raised and handled by the caller as it wishes.
- Previously a `WARNING` level log was always printed and None was returned. This assumes we know how the caller wants timeouts to be handled.
- Example: the DAS data_preload service intentionally times out because it doesn't care about the responses. Because of previous RpcPublisher code, `WARNING` logs were constantly printed to the console even when the service was performing nominally.
> Note: this is a breaking change! Risk Processor and DAS data_preload currently expect `send_request()` to catch TimeoutErrors for them, and this PR would cause uncaught errors unless their code changes first.
N/A
=> RpcPublisher: stop suppressing TimeoutError

python/idsse_common/idsse/common/protocol_utils.py, python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/idsse/common/utils.py
[IDSSE-1077](https://linear.app/idss/issue/IDSSE-1077)
[IDSSE-1301](https://linear.app/idss/issue/IDSSE-1301)
- Don't try to re-establish RabbitMQ connection inside of `Publisher`
- Catch `StreamLostError` pika exception as well?
- Look up `issueDt`s available in AWS for any dataset in parallel
- Default is 24 threads, which was pretty fast during testing. `ProtocolUtils.get_issues()` accepts a custom value with `max_workers` argument.
Previously the ProtocolUtils would sequentially crawl a given AWS bucket (such as NBM) to discover the most recent issuance datetimes available. 
- So each AWS S3 `ls` call would wait to complete before attempting to `ls` the next folder. This meant that `get_issues()` response time increased linearly as the `num_issues` argument increased. 
- Getting the …
=> feat: get issueDts from AWS in parallel

python/idsse_common/idsse/common/protocol_utils.py, python/idsse_common/test/test_aws_utils.py
[IDSSE-1077](https://linear.app/idss/issue/IDSSE-1077)
- Fix bug introduced by #113 where `get_issues()` mishandled requests with `numIssue: 1` where that issueDt actually had no validDts yet
This was causing DAS New Data to never find any NBM issueDts, so it was always publishing messages with `fields: {}` and no new NBM runs were being processed by the Engine.
Sadly my changes in #113 were naive. 
We can't just send `numIssue` number of network calls to AWS S3 in parallel, wait for the responses, and return the issueDt folders that had valid GRIB files in them. We have to use an ugly old for-loop, because we don't know beforehand how many AWS S3 folders will be empty.
- If `numIssue` is 1, by sending 1 AWS `ls` call we were only getting the latest issueDt--which is often an empty folder …
=> bug: get_issues() returning empty list

python/idsse_common/idsse/common/sci/grid_proj.py, python/idsse_common/idsse/common/sci/utils.py, python/idsse_common/test/sci/test_grid_proj.py
[IDSSE-1262](https://linear.app/idss/issue/IDSSE-1262)
- Add `slice_coords_to_slice_str()` function to GridProj
- Convert lat/lon coordinates (e.g. `[(100.50, -40), (95, -41)]`) into Cartesian (x/y) coordinates based on the Grid Projection (e.g. Lambert Conformal CONUS), then print it as a Python slice string
This logic was determined to be needed by two classes in DAS (slice_opr and product_key), but unfortunately one imports the other which caused a Circular Import error, so we need an external function that they both can import.
=> chore: add GridProj.slice_coords_to_slice_str()

python/idsse_common/idsse/common/log_util.py, python/idsse_common/idsse/common/schema/tags.json, python/idsse_common/idsse/common/sci/grid_proj.py, python/idsse_common/idsse/common/sci/utils.py, python/idsse_common/test/sci/test_grid_proj.py
[IDSSE-1373](https://linear.app/idss/issue/IDSSE-1373)
[IDSSE-1262](https://linear.app/idss/issue/IDSSE-1262)
- Update jsonschema to permit `CACHED` as one of statuses of Event Portfolio
- Add `slice_coords_to_slice_str()` function to GridProj
- Convert lat/lon coordinates (e.g. `[(100.50, -40), (95, -41)]`) into Cartesian (x/y) coordinates based on the Grid Projection (e.g. Lambert Conformal CONUS), then print it as a Python slice string
This will be used by the new "DSD Preload" service, which detects newly COMPLETE Event Portfolios, ensures that DAS web server builds cache responses for it, then republishes the portfolio with status `CACHED`.
This logic was determined to be needed by two classes in DAS (slice_opr and product_key), but unfortunately one imports the other which caused a …
=> chore: add "CACHED" to EP statuses

python/idsse_common/idsse/common/protocol_utils.py, python/idsse_common/idsse/common/rabbitmq_utils.py, python/idsse_common/test/test_aws_utils.py
[IDSSE-1301](https://linear.app/idss/issue/IDSSE-1301)
- Catch `ChannelWrongStateError` which pika throws if we attempt to publish messages to a closed channel/connection
Uncaught exception was causing callers of `Publisher.blocking_publish()` to still fail un-gracefully, because the services' code looks to the return value (`True`/`False`) to decide if it should restart its Publisher thread.
This catches yet another possible exception from pika and returns False to the caller, so the service can restart its Publisher.
=> bug: catch ChannelWrongStateError on publish
